AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  example app with ApiGateway, Lambda, DynamoDB.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5


Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      # Domain:
      # Auth:


  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: ApiGateway

  TopScoresFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/top_scores/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          HIGHSCORE_TABLE_NAME: !Ref HighscoreDBTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref HighscoreDBTable
      Events:
        GET:
          Type: Api
          Properties:
            Path: /topscores
            Method: get
            RestApiId:
              Ref: ApiGateway
        OPTIONS:
          Type: Api
          Properties:
            Path: /topscores
            Method: options
            RestApiId:
              Ref: ApiGateway

  ScoreWriteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/score/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          HIGHSCORE_TABLE_NAME: !Ref HighscoreDBTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HighscoreDBTable
      Events:
        POST:
          Type: Api
          Properties:
            Path: /score
            Method: post
            RequestParameters:
              - method.request.querystring.user:
                  Required: true
              - method.request.querystring.score:
                  Required: true
            RestApiId:
              Ref: ApiGateway
        OPTIONS:
          Type: Api
          Properties:
            Path: /score
            Method: options
            RestApiId:
              Ref: ApiGateway

  HighscoreDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
        - AttributeName: score
          AttributeType: N
        - AttributeName: LeaderboardPK
          AttributeType: S
      KeySchema:
        - AttributeName: user
          KeyType: HASH
        - AttributeName: score
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: LeaderboardByScore
          KeySchema:
            - AttributeName: LeaderboardPK
              KeyType: HASH
            - AttributeName: score
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: False

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
