name: Deploy ➜ Test ➜ Destroy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *' # Run at midnight on the first day of each month
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS Region for this run (overwrites samconfig.toml)"
        required: true
        default: "us-east-1"
      env_suffix:
        description: "Optional suffix for the dynamic stack name (e.g. feature-xyz)"
        required: false
        default: ""

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION_INPUT: ${{ inputs.aws_region || 'us-east-1' }}
  STACK_NAME: ${{ github.event.repository.name }}-${{ github.run_number }}${{ inputs.env_suffix && format('-{0}', inputs.env_suffix) || '' }}
  SAM_CLI_TELEMETRY: 0

jobs:
  deploy_and_refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gh-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION_INPUT }}

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      
      - name: Cache pip for build requirements
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/build-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install build requirements
        run: pip install -r scripts/build-requirements.txt

      # --- Overwrite stack_name and region in samconfig.toml (search & replace) ---
      - name: Patch samconfig.toml
        run: |
          CFG="samconfig.toml"
          [ -f "$CFG" ] || { echo "::error::$CFG not found"; exit 1; }
          sed -i "s/^stack_name\s*=.*/stack_name = \"${STACK_NAME}\"/" "$CFG"
          sed -i "s/^region\s*=.*/region = \"${AWS_REGION_INPUT}\"/" "$CFG"
          echo "### Effective samconfig.toml values:"
          grep -E '^(stack_name|region)\s*=' "$CFG"

      - name: Upload staged toml
        uses: actions/upload-artifact@v4
        with:
          name: staged-toml-artifact
          path: |            
            samconfig.toml
          if-no-files-found: error

      - name: Cache SAM build artifacts
        uses: actions/cache@v4
        with:
          path: .aws-sam
          key: ${{ runner.os }}-aws-sam
          restore-keys: |
            ${{ runner.os }}-aws-sam-

      - name: SAM Build
        run: sam build --parallel

      - name: SAM Deploy (uses samconfig.toml)
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

      - name: Refresh resource IDs
        run: ./refresh-resourceids.sh

      - name: Get resource dir name
        id: resdir
        run: |
          folder=$(./scripts/build_resource_dir_localname.sh)
          echo "$folder" > ./$folder/folder.txt
          echo "folder=$folder" >> "$GITHUB_OUTPUT"

      - name: Upload artifacts (resourceIds)
        uses: actions/upload-artifact@v4
        with:
          name: resource-ids
          # whatever I do, I get a flattened zip file...
          path: ${{ steps.resdir.outputs.folder }}
          include-hidden-files: true            # <- needed for ".resourceids-..."
          if-no-files-found: error

  run_tests:
    runs-on: ubuntu-latest
    needs: deploy_and_refresh
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pip for build requirements
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/build-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install build requirements
        run: pip install -r scripts/build-requirements.txt

      - name: Download refresh artifacts
        uses: actions/download-artifact@v4
        with:
          name: staged-toml-artifact
          path: ./artifacts

      - name: Use patched samconfig.toml
        run: cp ./artifacts/samconfig.toml ./samconfig.toml

      - name: Download refresh resource-ids artifacts
        uses: actions/download-artifact@v4
        with:
          name: resource-ids
          path: ./resourceids

      - name: Restore resourceids into place
        run: |
          set -e
          folder=$(cat ./resourceids/folder.txt)
          mkdir $folder
          cp ./resourceids/* ./$folder

      # Tests executed using repo run_* scripts (build URLs exactly like in repo)
      - name: Hello World
        run: |
          ./run_hello_world.sh | tee /tmp/hello.out
          test ${PIPESTATUS[0]} -eq 0

      - name: Create Scores
        run: |
          ./run_create_scores.sh | tee /tmp/create.out
          test ${PIPESTATUS[0]} -eq 0

      - name: Top Scores 
        run: |
          ./run_get_topscores.sh | tee /tmp/topscores.out
          test ${PIPESTATUS[0]} -eq 0

      - name: Test Top Scores
        run: |
          ./scripts/test_topscores.sh | tee /tmp/test-topscores.out
          test ${PIPESTATUS[0]} -eq 0

      - name: Upload test outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-outputs
          path: |
            /tmp/hello.out
            /tmp/create.out
            /tmp/topscores.out
            /tmp/test-topscores.out
          if-no-files-found: ignore

  destroy:
    runs-on: ubuntu-latest
    needs: [deploy_and_refresh, run_tests]
    if: always()
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gh-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION_INPUT }}

      - name: Cache pip for build requirements
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/build-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install build requirements
        run: pip install -r scripts/build-requirements.txt

      - name: Make delete script executable
        run: chmod +x ./delete-stack.sh

      - name: Download samconfig.toml
        uses: actions/download-artifact@v4
        with:
          name: staged-toml-artifact
          path: ./artifacts

      - name: Destroy stack (delete-stack.sh)
        run: |
          cp ./artifacts/samconfig.toml ./samconfig.toml
          ./delete-stack.sh --no-confirm
